services:
  comfyui:
    build: .
    image: comfyui:latest
    container_name: comfyui
    restart: unless-stopped

    networks:
      - comfyui_default
    ports:
      - "8188:8188"

    volumes:
      - .:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  comfyui_default:
    name: comfyui
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: comfyui_default